version: '3.8'

services:
  api:
    build:
      context: ./Posterr.API
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=develop2024;User=root;Password=test2024;
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test2024
      MYSQL_DATABASE: develop2024
    ports:
      - "3307:3306"
    volumes:
      - ./Assets/DB/init.sql:/docker-entrypoint-initdb.d/init.sql